version: '3.3'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    user: "${LOCAL_USER}:${LOCAL_USER}"
    network_mode: host
    volumes:
      - ./config/homeassistant:/config
      - /etc/localtime:/etc/localtime
    ports:
      - 8123:8123
    restart: always
  vscode:
    image: codercom/code-server:latest
    container_name: vscode
    user: "${LOCAL_USER}:${LOCAL_USER}"
    environment:
      DISABLE_AUTH: "true"
    volumes:
      - ./config/vscode:/home/coder/.config
      - ./config/homeassistant:/home/coder/project
    ports:
      - 8080:8080
    restart: always
  mosquitto:  
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    user: "${LOCAL_USER}:${LOCAL_USER}"
    volumes:
      - ./config/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    user: "${LOCAL_USER}:${LOCAL_USER}"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./config/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8081
    restart: always
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    volumes:
      - ./config/duplicati:/config
      - ./config:/backup
    ports:
      - 8200:8200
    restart: always